# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3289649201021993ffae57dbeca8c738cca73e4c30ae411813e6c1f656932be079e6fde3f4f551232d70ea650459ec326fe7aa0601d72418c19c6035d31a721

test:
  secret_key_base: d22dac5e3405863321539b0252ac08c1e616adb2ece3ec390abb1ca8b5ecb353bd19ba08910cb9e927f11664a370cf1a10d1f3d6b23a5b3bf7d9f0c2960d8e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
